import type { Metadata } from 'next';
import './globals.css';
import { Provider } from '@/context/themeProvider';
import Script from 'next/script';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="stylesheet" href="" />
      </Head>
      <body>
        <Provider>{children}</Provider>
          <Script defer id="googleTag" strategy="lazyOnload">{`
      setTimeout(function() {
          (function(w,d,s,l,i){
              w[l]=w[l]||[];
              w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
              j.defer=true;
              j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-NSKKPP2');
      }, 1500);
  `}</Script>
      </body>
    </html>
  );
}
